# Relaychain Configuration
relaychain:
  image: parity/polkadot:v0.9.27 # the docker image to use
  chain: rococo-local # the chain to use
  runtimeGenesisConfig: # additonal genesis override
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
  env: # environment variables for all relaychain nodes
    RUST_LOG: parachain::candidate-backing=trace
  flags: # additional CLI flags for all relaychain nodes
    - --rpc-methods=unsafe
  nodes: # nodes config
    - name: alice # the node name and session key, this imply `--alice`
      wsPort: 9944 # default ws port number is `9944 + global_node_index`
      rpcPort: 9933 # default rpc port number is `9933 + global_node_index`
      port: 30333 # default libp2p port number is `30333 + global_node_index`
      flags: # additional CLI flags for this node
        - --force-authoring
      env:
        RUST_LOG: babe=debug # environment varitables for this node
    - name: bob
    - name: charlie

# Parachain Configuration
parachains:
# Config for first parachain
- image: peaq_para_node:latest
  chain: # this could be a string like `dev` or a config object
    base: dev # the chain to use
    collators: # override collators
      - alice # this imply //Alice
    sudo: alice # override sudo key to //Alice
    runtimeGenesisConfig: # additonal genesis override
      balances:
        balances:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 10000000000000000]
  id: 2000 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    # - --force-authoring
    - --execution=wasm
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
  env: # environment variables for this parachain nodes
    RUST_LOG: sc_basic_authorship=trace
  volumePath: /data # The path to mount volume and base path, default to /data
  nodes: # nodes config
  - wsPort: 9947
    rpcPort: 9936
    port: 30336
    flags: # additional CLI flags for this node
      - --alice
    relaychainFlags: # additional CLI flags for relaychain part
      - --name=relaychain-alice
    env:
      RUST_LOG: aura=debug # environment varitables for this node
# Config for first parachain
- image: peaq_para_node:latest
  chain: # this could be a string like `dev` or a config object
    base: dev # the chain to use
    collators: # override collators
      - bob # this imply //Alice
    sudo: bob # override sudo key to //Alice
    runtimeGenesisConfig: # additonal genesis override
      balances:
        balances:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 10000000000000000]
  id: 3000 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    # - --force-authoring
    - --execution=wasm
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
  env: # environment variables for this parachain nodes
    RUST_LOG: sc_basic_authorship=trace
  volumePath: /data # The path to mount volume and base path, default to /data
  nodes: # nodes config
  - wsPort: 10047
    rpcPort: 10036
    port: 30436
    flags: # additional CLI flags for this node
      - --bob
    relaychainFlags: # additional CLI flags for relaychain part
      - --name=relaychain-bob
    env:
      RUST_LOG: aura=debug # environment varitables for this node
