# Relaychain Configuration
relaychain:
  image: parity/polkadot:v0.9.42 # the docker image to use
  chain: rococo-local # the chain to use
  runtimeGenesisConfig: # additonal genesis override
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
  env: # environment variables for all relaychain nodes
    RUST_LOG: parachain::candidate-backing=trace
  flags: # additional CLI flags for all relaychain nodes
    - --rpc-methods=unsafe
  nodes: # nodes config
    - name: alice # the node name and session key, this imply `--alice`
      wsPort: 9944 # default ws port number is `9944 + global_node_index`
      rpcPort: 9933 # default rpc port number is `9933 + global_node_index`
      port: 30333 # default libp2p port number is `30333 + global_node_index`
      flags: # additional CLI flags for this node
        - --force-authoring
      env:
        RUST_LOG: babe=debug # environment varitables for this node
    - name: bob

# Parachain Configuration
parachains:
# Config for first parachain
- image: peaq_para_node:latest
  chain: # this could be a string like `dev` or a config object
    base: dev-local # the chain to use
    chainType: Development
    collators: # override collators
      - ferdie
    sudo: alice # override sudo key to //Alice
    runtimeGenesisConfig: # additonal genesis override
      balances:
        balances:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 1000000000000000000000]
          - [5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty, 1000000000000000000000]
          - [5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y, 1000000000000000000000]
          - [5DAAnrj7VHTznn2AWBemMuyBwZWs6FNFjdyVXUeYum3PTXFy, 1000000000000000000000]
          - [5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw, 1000000000000000000000]
          - [5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL, 1000000000000000000000]

  id: 3001 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    # - --force-authoring
    - --execution=wasm
    - --state-pruning=archive
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
  env: # environment variables for this parachain nodes
    RUST_LOG: sc_basic_authorship=trace
  volumePath: /data # The path to mount volume and base path, default to /data
  nodes: # nodes config
  - name: ferdie
    wsPort: 9947
    rpcPort: 9936
    port: 30336
    flags: # additional CLI flags for this node
      - --ferdie
    relaychainFlags: # additional CLI flags for relaychain part
      - --name=relaychain-ferdie
    env:
      RUST_LOG: aura=debug # environment varitables for this node
