#!/bin/sh

# Parachin chains configurataion files
FORKED_CONFIG_FILE="config.parachain.agung.forked.yml"
RPC_ENDPOINT="https://rpcpc1-qa.agung.peaq.network"
DOCKER_COMPOSE_FOLDER="yoyo"
FORK_FOLDER="/home/jaypan/Work/peaq/fork-test/fork-binary/peaq-dev-v06042023"

real_path=$(realpath "$DOCKER_COMPOSE_FOLDER")
if [ "$real_path" = "/" ]; then
  echo "Please reset the DOCKER_COMPOSE_FOLDER, $DOCKER_COMPOSE_FOLDER, variable in the script"
  exit 1
fi

# Below variables are internal used, no need to change it
# These files are generated by the parachain-launch
# But below files are changed by the configuration
rococo_config_file="rococo-local.json"
now_parachain_file_name="dev-2000.json"
host_rococo_config_file=${DOCKER_COMPOSE_FOLDER}/${rococo_config_file}
polkadot_image=`cat ${FORKED_CONFIG_FILE} | grep image | grep polkadot | awk -F': ' '{print $2}' | awk '{print $1}'`
if command -p docker-compose >/dev/null 2>&1
then
  docker_compose_cmd="docker-compose"
else
  docker_compose_cmd="docker compose"
fi

# Stop the docker-compose and regenerate
(cd ${DOCKER_COMPOSE_FOLDER}; ${docker_compose_cmd} down -v)
rm -rf ${DOCKER_COMPOSE_FOLDER} || true
(./bin/parachain-launch generate --config="${FORKED_CONFIG_FILE}" --output=${DOCKER_COMPOSE_FOLDER})


# Copy file to the fork position
cp ${DOCKER_COMPOSE_FOLDER}/$now_parachain_file_name $FORK_FOLDER/parachain.plaintext.config

# Run the fork
( \
 cd fork-off-substrate; \
 env ALICE=1 \
 SOURCE_FOLDER=${FORK_FOLDER} \
 RPC_ENDPOINT=${RPC_ENDPOINT}\
 sh forked.generated.sh; \
)

# Copy the forked file to the parachain-launch folder
pwd
cp $FORK_FOLDER/output/fork.json ${DOCKER_COMPOSE_FOLDER}/$now_parachain_file_name

new_genesis_code=$(cat $FORK_FOLDER/output/fork.json.genesis)
# Replace the rococo's parchain genesis file
sed -i "s/\"genesis_head\": \".*\"/\"genesis_head\": \"$new_genesis_code\"/" ${host_rococo_config_file}.original.json

PWD=`pwd`
docker run --rm -v "${PWD}/${host_rococo_config_file}.original.json":/${rococo_config_file} ${polkadot_image} build-spec --raw --chain=/${rococo_config_file} --disable-default-bootnode > ${host_rococo_config_file}

cd ${DOCKER_COMPOSE_FOLDER}
${docker_compose_cmd} up -d --build --remove-orphans
