# Relaychain Configuration
relaychain:
  image: parity/polkadot:v1.8.0 # the docker image to use
  chain: rococo-local # the chain to use
  runtimeGenesisConfig: # additonal genesis override
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
        async_backing_params:
          max_candidate_depth: 3
          allowed_ancestry_len: 2
        scheduling_lookahead: 2
  env: # environment variables for all relaychain nodes
    RUST_LOG: parachain::candidate-backing=trace,xcm=trace
  flags: # additional CLI flags for all relaychain nodes
    - --rpc-methods=unsafe
    - --no-hardware-benchmarks
    - --insecure-validator-i-know-what-i-do
    # - --unsafe-force-node-key-generation
  nodes: # nodes config
    - name: alice # the node name and session key, this imply `--alice`
      wsPort: 10044 # default ws port number is `9944 + global_node_index`
      rpcPort: 10033 # default rpc port number is `9933 + global_node_index`
      port: 40333 # default libp2p port number is `30333 + global_node_index`
    - name: bob
      wsPort: 10045
      rpcPort: 10034
      port: 40334
    - name: charlie
      wsPort: 10046
      rpcPort: 10035
      port: 40335

# Parachain Configuration
parachains:
# Config for first parachain
- image: peaq/parachain:peaq-v0.0.104
  chain: # this could be a string like `dev` or a config object
    base: peaq-local # the chain to use
    chainType: Development
    collators: # override collators
      - alice
      - bob
      - charlie
      - dave
      - eve
      - ferdie
    sudo: alice # override sudo key to //Alice
    runtimeGenesisConfig: # additonal genesis override
      balances:
        balances:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 1000000000000000000000]
          - [5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty, 1000000000000000000000]
          - [5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y, 1000000000000000000000]
          - [5DAAnrj7VHTznn2AWBemMuyBwZWs6FNFjdyVXUeYum3PTXFy, 1000000000000000000000]
          - [5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw, 1000000000000000000000]
          - [5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL, 1000000000000000000000]
  id: 3338 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    # - --force-authoring
    - --execution=wasm
    - --state-pruning=archive
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
  env: # environment variables for this parachain nodes
    RUST_LOG: sc_basic_authorship=trace,xcm=trace
  volumePath: /chain-data # The path to mount volume and base path, default to /data
  nodes: # nodes config
    - wsPort: 9944
      rpcPort: 9933
      port: 30336
      flags: # additional CLI flags for this node
        - --alice
    - wsPort: 9945
      rpcPort: 9934
      port: 30337
      flags:
        - --bob
    - wsPort: 9946
      rpcPort: 9935
      port: 30338
      flags:
        - --charlie
    - wsPort: 9947
      rpcPort: 9936
      port: 30339
      flags:
        - --dave
    - wsPort: 9948
      rpcPort: 9937
      port: 30340
      flags:
        - --eve
    - wsPort: 9949
      rpcPort: 9938
      port: 30341
      flags:
        - --ferdie
    - wsPort: 9950
      rpcPort: 9939
      port: 30342
    - wsPort: 9951
      rpcPort: 9940
      port: 30343
    - wsPort: 9952
      rpcPort: 9941
      port: 30344
# Config for xcm parachain
- image: peaq/parachain:peaq-v0.0.104
  chain: # this could be a string like `dev` or a config object
    base: dev-local # the chain to use
    chainType: Development
    collators: # override collators
      - ferdie
      # - dave
      # - eve
    sudo: alice # override sudo key to //Alice
    runtimeGenesisConfig: # additonal genesis override
      balances:
        balances:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 1000000000000000000000]
          - [5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty, 1000000000000000000000]
          - [5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y, 1000000000000000000000]
          - [5DAAnrj7VHTznn2AWBemMuyBwZWs6FNFjdyVXUeYum3PTXFy, 1000000000000000000000]
          - [5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw, 1000000000000000000000]
          - [5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL, 1000000000000000000000]
  id: 3000 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    # - --force-authoring
    - --execution=wasm
    - --state-pruning=archive
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
  env: # environment variables for this parachain nodes
    RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=trace,xcm=trace,cumulus-pov-recovery=trace,cumulus-pallet-aura-ext=trace,cumulus-pallet-parachain-system=trace,cumulus-primitives-aura=trace
  volumePath: /chain-data # The path to mount volume and base path, default to /data
  nodes: # nodes config
    - name: ferdie
      wsPort: 10144
      rpcPort: 10133
      port: 30533
      flags: # additional CLI flags for this node
        - --ferdie
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-ferdie
