# Relaychain Configuration
relaychain:
  image: parity/polkadot:v1.13.0 # the docker image to use
  chain: westend-local # the chain to use
  runtimeGenesisConfig: # additonal genesis override
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
        async_backing_params:
          max_candidate_depth: 3
          allowed_ancestry_len: 2
  env: # environment variables for all relaychain nodes
    RUST_LOG: parachain::candidate-backing=trace,xcm=trace
  flags: # additional CLI flags for all relaychain nodes
    - --rpc-methods=unsafe
    - --no-hardware-benchmarks
    - --insecure-validator-i-know-what-i-do
    - --unsafe-force-node-key-generation
  nodes: # nodes config
    - name: alice # the node name and session key, this imply `--alice`
      wsPort: 10044 # default ws port number is `9944 + global_node_index`
      rpcPort: 10033 # default rpc port number is `9933 + global_node_index`
      port: 40333 # default libp2p port number is `30333 + global_node_index`
    - name: bob
      wsPort: 10045
      rpcPort: 10034
      port: 40334
    - name: charlie
      wsPort: 10046
      rpcPort: 10035
      port: 40335

# Parachain Configuration
parachains:
# Config for first parachain
- image: peaq/parachain:peaq-v0.0.103
  chain: # this could be a string like `dev` or a config object
    base: peaq-local # the chain to use
    chainType: Development
    collators: # override collators
      - ferdie
    sudo: alice # override sudo key to //Alice
    runtimeGenesisConfig: # additonal genesis override
      balances:
        balances:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 1000000000000000000000]
          - [5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty, 1000000000000000000000]
          - [5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y, 1000000000000000000000]
          - [5DAAnrj7VHTznn2AWBemMuyBwZWs6FNFjdyVXUeYum3PTXFy, 1000000000000000000000]
          - [5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw, 1000000000000000000000]
          - [5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL, 1000000000000000000000]
          ### For collators
          - [5EDFZ1kVq1Ma3w5UZhg8ccPRzMoKmr29XZ2nDB6RSD4ZGpT1, 60000000000000000000000]
          - [5EHzSPk1T8VxUASiG9wEtxSR3ykDhvAEhYseF1ViqkuoBN5y, 60000000000000000000000]
          - [5DNr8eH9o2eyNhfZQMgqnEMaR94c1dufQNo3ojhkfWb1k3YJ, 60000000000000000000000]
          - [5DCi5nd6UFGDtojFbSbJ4uaCPc3TvikdmYP1LhMARNaf2gSe, 60000000000000000000000]
          - [5Df46VdyJuJEXcocAYkfsmukLzKr5F6kcMXuBSnRvwQvZy9A, 60000000000000000000000]
          - [5DyRH5xWVPXZWTdPeEr1VEc1MMY1jvg4faNfGPmRm54Qfw1v, 60000000000000000000000]
          - [5ELWmrn5Q3UivEqh8jTYgHtdxeyphMT3gReeWBAtv5VMBSwd, 60000000000000000000000]
          ### For delegators
          - [5GjRpM4wEB6KDDzekm6tWEeaAu8HE8ZHT2r586mf2aJorAR1, 60000000000000000000000]
          - [5HT1BVyp6Bidt7bNebvEr6h2a3EC5bZFxPnJDnFGNkpNTsWr, 60000000000000000000000]
          - [5HWE7FwLjyBHbQcedCvdCYp83FFkX1KvGJrVG9yDwofSf91z, 60000000000000000000000]
          - [5D2G1T3T9m6K889CdidHroubmLh8j6PNCDwnNQZPgpRPWmz3, 60000000000000000000000]
          - [5EjToxcyVwyPMpYzaMrzfQczr8JBr1BaKkFkLJ1tkFwqT1Eb, 60000000000000000000000]
          - [5Dqm7d56CiekJhPTtFPhkvN8gDeU3SqUY6UHwT9fQzAMqXyn, 60000000000000000000000]
          - [5H3bFVK1SmKABJka5kUbjv3FNoXYnssN6GCvGWTumkZQcyKR, 60000000000000000000000]
          - [5E2LsWXpqabsB8PSgBa8EhWfx5CgxBztp9ofXjqZteABVyHJ, 60000000000000000000000]
          ### For one delegator to multi collators
          - [5H6BC6Qm4yLE3KgPUEEgKtRWjNGEwDMsXAGhaS8ZDta4fgGX, 60000000000000000000000]

  id: 3338 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    # - --force-authoring
    - --execution=wasm
    - --state-pruning=archive
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
  env: # environment variables for this parachain nodes
    RUST_LOG: sc_basic_authorship=trace,xcm=trace
  volumePath: /chain-data # The path to mount volume and base path, default to /data
  nodes: # nodes config
    - wsPort: 9944
      rpcPort: 9933
      port: 30336
      flags: # additional CLI flags for this node
        - --ferdie
    - wsPort: 9945
      rpcPort: 9934
      port: 30337
    - wsPort: 9946
      rpcPort: 9935
      port: 30338
    - wsPort: 9947
      rpcPort: 9936
      port: 30339
    - wsPort: 9948
      rpcPort: 9937
      port: 30340
    - wsPort: 9949
      rpcPort: 9938
      port: 30341
    - wsPort: 9950
      rpcPort: 9939
      port: 30342
    - wsPort: 9951
      rpcPort: 9940
      port: 30343
    - wsPort: 9952
      rpcPort: 9941
      port: 30344
# Config for xcm parachain
# TODO We should use 104 because 103 didn't support the XCM remote exeuction
- image: peaq/parachain:peaq-v0.0.103
  chain: # this could be a string like `dev` or a config object
    base: dev-local # the chain to use
    chainType: Development
    collators: # override collators
      - ferdie
      # - dave
      # - eve
    sudo: alice # override sudo key to //Alice
    runtimeGenesisConfig: # additonal genesis override
      balances:
        balances:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 1000000000000000000000]
          - [5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty, 1000000000000000000000]
          - [5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y, 1000000000000000000000]
          - [5DAAnrj7VHTznn2AWBemMuyBwZWs6FNFjdyVXUeYum3PTXFy, 1000000000000000000000]
          - [5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw, 1000000000000000000000]
          - [5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL, 1000000000000000000000]
  id: 3000 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    # - --force-authoring
    - --execution=wasm
    - --state-pruning=archive
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
  env: # environment variables for this parachain nodes
    RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=trace,xcm=trace,cumulus-pov-recovery=trace,cumulus-pallet-aura-ext=trace,cumulus-pallet-parachain-system=trace,cumulus-primitives-aura=trace
  volumePath: /chain-data # The path to mount volume and base path, default to /data
  nodes: # nodes config
    - name: ferdie
      wsPort: 10144
      rpcPort: 10133
      port: 30533
      flags: # additional CLI flags for this node
        - --ferdie
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-ferdie
