# Relaychain Configuration
relaychain:
  image: parity/polkadot:v1.0.0 # the docker image to use
  chain: rococo-local # the chain to use
  runtimeGenesisConfig: # additonal genesis override
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
    hrmp:
      preopenHrmpChannels:
        - sender: 3000
          recipient: 3338
          maxCapacity: 8
          maxMessageSize: 102400
        - sender: 3338
          recipient: 3000
          maxCapacity: 8
          maxMessageSize: 102400
  env: # environment variables for all relaychain nodes
    RUST_LOG: parachain::candidate-backing=trace,xcm=trace
  flags: # additional CLI flags for all relaychain nodes
    - --rpc-methods=unsafe
  nodes: # nodes config
    - name: alice # the node name and session key, this imply `--alice`
      wsPort: 9944 # default ws port number is `9944 + global_node_index`
      rpcPort: 9933 # default rpc port number is `9933 + global_node_index`
      port: 30333 # default libp2p port number is `30333 + global_node_index`
      flags: # additional CLI flags for this node
        - --force-authoring
    - name: bob
    - name: charlie

# Parachain Configuration
parachains:
# Config for first parachain
- image: peaq/parachain:peaq-v0.0.7
  chain: # this could be a string like `dev` or a config object
    base: peaq-local # the chain to use
    chainType: Development
    collators: # override collators
      - ferdie
      # - dave
    sudo: alice # override sudo key to //Alice
    runtimeGenesisConfig: # additonal genesis override
      balances:
        balances:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 1000000000000000000000]
          - [5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty, 1000000000000000000000]
          - [5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y, 1000000000000000000000]
          - [5DAAnrj7VHTznn2AWBemMuyBwZWs6FNFjdyVXUeYum3PTXFy, 1000000000000000000000]
          - [5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw, 1000000000000000000000]
          - [5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL, 1000000000000000000000]
  id: 3338 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    # - --force-authoring
    - --execution=wasm
    - --state-pruning=archive
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
  env: # environment variables for this parachain nodes
    RUST_LOG: sc_basic_authorship=trace,xcm=trace
  volumePath: /chain-data # The path to mount volume and base path, default to /data
  nodes: # nodes config
    - wsPort: 10044
      rpcPort: 10033
      port: 40336
      flags: # additional CLI flags for this node
        - --ferdie
    # - wsPort: 10045
    #   rpcPort: 10034
    #   port: 40337
    #   flags:
    #     - --dave
- image: acala/acala-node:2.21.0
  chain:
    base: acala-local
    collators:
      - bob
    sudo: alice
    runtimeGenesisConfig: # additonal genesis override
      balances:
        balances:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 1000000000000000000000]
          - [5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty, 1000000000000000000000]
          - [5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y, 1000000000000000000000]
          - [5DAAnrj7VHTznn2AWBemMuyBwZWs6FNFjdyVXUeYum3PTXFy, 1000000000000000000000]
          - [5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw, 1000000000000000000000]
          - [5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL, 1000000000000000000000]
  id: 3000
  parachain: true
  flags:
    - --rpc-methods=unsafe
    - --force-authoring
    - --wasm-execution=compiled
    - --execution=wasm
  relaychainFlags:
    - --wasm-execution=compiled
    - --execution=wasm
  env:
    RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug,xcm=trace
  # Acala's path should be under the acala/data
  volumePath: /acala/data
  nodes: # nodes config
    - name: bob # the node name and session key, this imply `--alice`
      wsPort: 10144 # default ws port number is `9944 + global_node_index`
      rpcPort: 10133 # default rpc port number is `9933 + global_node_index`
      port: 30533 # default libp2p port number is `30333 + global_node_index`
      flags:
        - --bob
      relaychainFlags: # additional CLI flags for relaychain part
