# Relaychain Configuration
relaychain:
  image: parity/polkadot:v1.8.0 # the docker image to use
  chain: rococo-local # the chain to use
  runtimeGenesisConfig: # additonal genesis override
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
        async_backing_params:
          max_candidate_depth: 3
          allowed_ancestry_len: 2
        scheduling_lookahead: 2
  env: # environment variables for all relaychain nodes
    RUST_LOG: parachain::candidate-backing=trace,xcm=trace
  flags: # additional CLI flags for all relaychain nodes
    - --rpc-methods=unsafe
    - --no-hardware-benchmarks
    - --insecure-validator-i-know-what-i-do
    # - --unsafe-force-node-key-generation
  nodes: # nodes config
    - name: alice # the node name and session key, this imply `--alice`
      wsPort: 9944 # default ws port number is `9944 + global_node_index`
      rpcPort: 9933 # default rpc port number is `9933 + global_node_index`
      port: 30333 # default libp2p port number is `30333 + global_node_index`
    - name: bob
    - name: charlie

# Parachain Configuration
parachains:
# Config for first parachain
- image: sfffaaa/peat-test:peaq-token-economy-v1-240509
  chain: # this could be a string like `dev` or a config object
    base: peaq-local # the chain to use
    chainType: Development
    collators: # override collators
      - ferdie
      # - dave
    sudo: alice # override sudo key to //Alice
    runtimeGenesisConfig: # additonal genesis override
      balances:
        balances:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 1000000000000000000000]
          - [5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty, 1000000000000000000000]
          - [5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y, 1000000000000000000000]
          - [5DAAnrj7VHTznn2AWBemMuyBwZWs6FNFjdyVXUeYum3PTXFy, 1000000000000000000000]
          - [5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw, 1000000000000000000000]
          - [5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL, 1000000000000000000000]
  id: 3338 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    # - --force-authoring
    - --execution=wasm
    # - --state-pruning=archive
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
  env: # environment variables for this parachain nodes
    RUST_LOG: sc_basic_authorship=trace
  volumePath: /chain-data # The path to mount volume and base path, default to /data
  nodes: # nodes config
    - wsPort: 10044
      rpcPort: 10033
      port: 40333
      flags: # additional CLI flags for this node
        - --ferdie
    - name: collator-0
      wsPort: 10045
      rpcPort: 20034
      port: 30434
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-0
    - name: collator-1
      wsPort: 10046
      rpcPort: 20035
      port: 30435
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-1
    - name: collator-2
      wsPort: 10047
      rpcPort: 20036
      port: 30436
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-2
    - name: collator-3
      wsPort: 10048
      rpcPort: 20037
      port: 30437
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-3
    - name: collator-4
      wsPort: 10049
      rpcPort: 20038
      port: 30438
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-4
    - name: collator-5
      wsPort: 10050
      rpcPort: 20039
      port: 30439
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-5
    - name: collator-6
      wsPort: 10051
      rpcPort: 20040
      port: 30440
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-6
    - name: collator-7
      wsPort: 10052
      rpcPort: 20041
      port: 30441
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-7
    - name: collator-8
      wsPort: 10053
      rpcPort: 20042
      port: 30442
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-8
    - name: collator-9
      wsPort: 10054
      rpcPort: 20043
      port: 30443
      relaychainFlags: # additional CLI flags for relaychain part
        - --name=relaychain-9
